// Module included in the following assemblies:
// * service_mesh/v2x/-ossm-troubleshooting-istio.adoc

[id="ossm-validating-operators_{context}"]
= Validating Operator installation

//The Operator installation steps include verifying the Operator status in the OpenShift console.

When you install the {ProductName} Operators, OpenShift automatically creates the following objects as part of a successful Operator installation:

* ConfigMaps
* CustomResourceDefinitions
* Deployments
* Pods
* ReplicaSets
* Roles
* RoleBindings
* Secrets
* Service Accounts
* Services

.From the Openshift console

You can verify the Operator pods are available and running in the OpenShift Console.

. Navigate to *Workloads* -> *Pods*.
. Select the `openshift-operators` namespace.
. Verify that the following Pods exist and have a status of `running`.
** istio-operator
** jager-operator
** kiali-operator
. Select the `openshift-operators-redhat` namespace.
. Verify that the `elasticsearch-operator` Pod exists and has a status of `running`.

.From the command line
You can verify the Operator pods are available and running in the `openshift-operators` namespace with the following command:

[source,terminal]
----
$ oc get pods -n openshift-operators
----

You should see something similar to the following:

[source,terminal]
----
NAME                               READY   STATUS    RESTARTS   AGE
istio-operator-bb49787db-zgr87     1/1     Running   0          15s
jaeger-operator-7d5c4f57d8-9xphf   1/1     Running   0          2m42s
kiali-operator-f9c8d84f4-7xh2v     1/1     Running   0          64s
----

Verify the Elasticsearch operator with the following command:

[source,terminal]
----
$ oc get pods -n openshift-operators-redhat
----

You should see something similar to the following:
[source,terminal]
----
NAME                                      READY   STATUS    RESTARTS   AGE
elasticsearch-operator-d4f59b968-796vq     1/1     Running   0          15s
----
