// Module included in the following assemblies:
// * service_mesh/v2x/ossm-deploy-mod-v2x.adoc

[id="ossm-deploy-multitenant_{context}"]
= Multitenant deployment model

[role="_abstract"]
{ProductName} installs a `ServiceMeshControlPlane` that is configured for multitenancy by default. {ProductName} uses a multitenant Operator to manage the control plane lifecycle. Within a mesh, namespaces are used for tenancy.

Typical service mesh deployments use a single control plane to configure communication between services in the mesh. {ProductName} supports “soft multi-tenancy”, where there is one control plane and one mesh per tenant, and there can be multiple independent control planes within the cluster. Multitenant deployments specify the projects that can access the {ProductShortName} and isolate the {ProductShortName} from other control plane instances.

The cluster administrator gets control and visibility across all the Istio control planes, while the tenant administrator only gets control over their specific {ProductShortName}, Kiali, and Jaeger instance.

You can grant a team permission to deploy its workloads only to a given namespace or set of namespaces.  If granted the `mesh-user` role by the service mesh administrator, users can create a `ServiceMeshMember` resource to add namespaces to the `ServiceMeshMemberRoll`.
