// Module included in the following assemblies:
// * service_mesh/v2x/-ossm-troubleshooting-istio.adoc

[id="ossm-troubleshooting-smcp_{context}"]
= Troubleshooting the service mesh control plane







If you experienced issues while deploying the `ServiceMeshControlPlane`,


* The `ServiceMeshControlPlane` resource must be installed in a project that is separate from your microservices and Operators.   This documentation uses `istio-system` as an example, but you can deploy your control plane in any project as long as it is separate from the project that contains your Operators and services.

* The ServiceMeshControlPlane and Jaeger custom resource must be deployed in the same namespace.  For example, `istio-system`.

//* If you selected to install the Elasticsearch Operator in a specific namespace in the cluster instead of selecting *All namespaces in on the cluster (default)*, then OpenShift could not automatically copy the Operator to the istio-system namespace and the Jaeger Operator could not call the  Elasticsearch Operator during the installation?

//The steps for deploying the service mesh control plane (SMCP) include verifying the deployment in the OpenShift console.
