// Module included in the following assemblies:
//
// -service_mesh/v2x/ossm-architecture.adoc

[id="ossm-architecture_{context}"]
= Service Mesh architecture

Service mesh technology operates at the network communication level. That is, service mesh components capture or intercept traffic to and from microservices, either modifying requests, redirecting them, or creating new requests to other services.

At a high level, {ProductName} consists of a data plane and a control plane:

The *data plane* is a set of intelligent proxies that intercept and control all inbound and outbound network communication between microservices in the service mesh.
The data plane is implemented in such a way that it intercepts all inbound (ingress) and outbound (egress) network traffic. The Istio data plane is composed of Envoy sidecar proxies running in the same network space as each service to control all network communication between services.

* *Envoy proxies* are the only Istio components that interact with data plane traffic. All incoming (ingress) and outgoing (egress) network traffic between services flows through the proxies. The Envoy proxy also collects all metrics related to the services in the mesh. Envoy proxies are deployed as sidecars, in the same pod as services, and as well as gateways.

** *Sidecar proxies* manage inbound and outbound communication to the workload instance it is attached to.

** *Gateways* are proxies operating as load balancers receiving incoming or outgoing HTTP/TCP connections. Gateway configurations are applied to standalone Envoy proxies that are running at the edge of the mesh, rather than sidecar Envoy proxies running alongside your service workloads. You use a Gateway to manage inbound and outbound traffic for your mesh, letting you specify which traffic you want to enter or leave the mesh.

*** *Ingress-gateway* - Also known as an ingress controller, the Ingress Gateway is a dedicated Envoy proxy that receives and controls traffic entering the service mesh. An Ingress Gateway allows features such as monitoring and route rules to be applied to traffic entering the cluster.

*** *Egress-gateway* - Also known as an egress controller, the Egress Gateway is a dedicated Envoy proxy that manages traffic leaving the service mesh. An Egress Gateway allows features such as monitoring and route rules to be applied to traffic exiting the mesh.

The *control plane* manages and configures the proxies that make up the data plane. It is the authoritative source for configuration, enforces access control and usage policies, and collects metrics from the proxies in the service mesh.

* The Istio control plane is composed of *Istiod* which consolidates several previous control plane components (Citadel, Galley, Pilot) into a single binary. Istiod provides service discovery, configuration and certificate management. It converts high-level routing rules to Envoy configurations and propagates them to the sidecars at runtime.

** Istiod acts as a Certificate Authority (CA) and generates certificates to allow secure mTLS communication in the data plane.

** Secret Discovery Service (SDS) distributes certificates and keys to sidecars directly from Istiod.

** Istiod automatically injects sidecar proxies to services whenever that service is deployed to an OpenShift cluster.

{ProductName} uses the *istio-operator* to manage the installation of the control plane. An _Operator_ is a piece of software that enables you to implement and automate common activities in your OpenShift cluster. It acts as a controller, allowing you to set or change the desired state of objects in your cluster.

{ProductName} also bundles the following Istio addons as part of the product:

* *Kiali* - Kiali is the management console for {ProductName}. It provides dashboards, observability, and robust configuration and validation capabilities. It shows the structure of your service mesh by inferring traffic topology and displays the health of your mesh. Kiali provides detailed metrics, powerful validation, access to Grafana, and strong integration for distributed tracing with Jaeger.

* *Prometheus* - {ProductName} uses Prometheus to store telemetry information from services. Kiali depends on Prometheus to obtain metrics, health status, and mesh topology.

* *Jaeger* - {ProductName} supports Jaeger for distributed tracing. Jaeger is an open source traceability server that centralizes and displays traces associated with a single request between multiple services. Using Jaeger you can monitor and troubleshoot your microservices-based distributed systems.

* *Elasticsearch* - ElasticSearch is an open source, distributed, JSON-based search and analytics engine. Jaeger relies on ElasticSearch for distributed storage and indexing for logging and tracing data.

* *Grafana* - Grafana provides mesh administrators with advanced query and metrics analysis and dashboards for Istio data. Optionally, Grafana can be used to analyze service mesh metrics.

Istio Adapters

* *3scale* - The 3scale Istio adapter is an optional component that integrates {ProductName} with Red Hat 3scale API Management solutions. The default {ProductName} installation does not include this component.
