////
This PROCEDURE module included in the following assemblies:
* service_mesh/v1x/prepare-to-deploy-applications-ossm.adoc
* service_mesh/v2x/prepare-to-deploy-applications-ossm.adoc
////

[id="ossm-tutorial-bookinfo-verify-install_{context}"]
= Verifying the Bookinfo installation

Before configuring your application, verify that it successfully deployed.

.Prerequisites

* {ProductName} {ProductVersion} installed.
* Access to the {product-title} Command-line Interface (CLI) also known as `oc`.
* Complete the steps for installing the Bookinfo sample app.

.Procedure

. Log in to the {product-title} CLI.

. Verify that all pods are ready with this command:
+
[source,terminal]
----
$ oc get pods -n bookinfo
----
+
You should receive a response `200`.
+
** Alternatively, you can open `http://$GATEWAY_URL/productpage` in your browser.
** You can also verify that all pods are ready with this command:
+
[source,terminal]
----
echo "http://$GATEWAY_URL/productpage"
----
+
You should see output similar to the following:
+
[source,terminal]
----
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-55b869668-jh7hb        2/2     Running   0          12m
productpage-v1-6fc77ff794-nsl8r   2/2     Running   0          12m
ratings-v1-7d7d8d8b56-55scn       2/2     Running   0          12m
reviews-v1-868597db96-bdxgq       2/2     Running   0          12m
reviews-v2-5b64f47978-cvssp       2/2     Running   0          12m
reviews-v3-6dfd49b55b-vcwpf       2/2     Running   0          12m
----
