// Module included in the following assemblies:
//
// * service_mesh/v2x/customizing-installation-ossm.adoc


[id="ossm-specifying-external-jaeger_{context}"]
= Specifying Jaeger configuration in a Jaeger custom resource

Configuring Jaeger in the Jaeger custom resource rather than in the `ServiceMeshControlPlane` lets you fully customize your Jaeger deployment.  This configuration is sometimes referred to as an "external Jaeger" since the configuration is specified outside of the SMCP.

[NOTE]
====
The `ServiceMeshControlPlane` and Jaeger custom resource must be deployed in the same namespace.  For example, `istio-system`.
====

You can configure and deploy a standalone Jaeger instance and then specify the `name` of the Jaeger resource as the value for `spec.addons.jaeger.name` in the `ServiceMeshControlPlane` resource.  If a Jaeger resource matching the value of `name` exists, the control plane will use the existing installation.  This approach lets you fully customize your Jaeger configuration.
