// Module included in the following assemblies:
// * service_mesh/v2x/-ossm-troubleshooting-istio.adoc

[id="ossm-troubleshooting-operators_{context}"]
= Troubleshooting service mesh Operators

If you experience Operator issues,

* Verify your Operator subscription status.
* Verify that you did not inadvertently install a community Operator.
* You can only install Operators through the OpenShift console, the OperatorHub is not accessible from the command line.
//You must have the cluster-admin role to install Red Hat OpenShift Service Mesh.  Is there a warning?

* Check for any errors in the operator pod logs if the issue is related to installation of operators.


You can view Operator logs by using the `oc logs` command.  Red Hat may request logs to help resolve support cases.
[source,terminal]
----
$ oc logs -n openshift-operators <podName>
----
For example,
[source,terminal]
----
$ oc logs -n openshift-operators istio-operator-bb49787db-zgr87
----

//If your pod is failing to start, you may need to use the `--previous` option to see the logs of the last attempt.
